version: "3.7"

services:
  database_rpgapi:
    image: postgres
    container_name: database_rpgapi
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=database_rpgapi
      - POSTGRES_DB=rpgapi
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rpgapi
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_rpgapi
    depends_on:
      - database_rpgapi
volumes:
  pgdata:
    driver: local